# Generated by Django 2.2.7 on 2019-11-14 03:00

from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('symbol', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='Concept',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('attributes', djongo.models.fields.ArrayReferenceField(blank=True, default=list, on_delete=djongo.models.fields.ArrayReferenceField._on_delete, to='solver.Attribute')),
            ],
        ),
        migrations.CreateModel(
            name='Equation',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('syntax', models.TextField()),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('parent_concept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solver.Concept')),
            ],
        ),
        migrations.AddField(
            model_name='concept',
            name='equations',
            field=djongo.models.fields.ArrayReferenceField(blank=True, default=list, on_delete=djongo.models.fields.ArrayReferenceField._on_delete, to='solver.Equation'),
        ),
        migrations.AddField(
            model_name='attribute',
            name='parent_concept',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solver.Concept'),
        ),
    ]
