# Generated by Django 2.2.7 on 2019-11-14 03:14

from django.db import migrations
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('solver', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concept',
            name='attributes',
            field=djongo.models.fields.ArrayReferenceField(blank=True, on_delete=djongo.models.fields.ArrayReferenceField._on_delete, to='solver.Attribute'),
        ),
        migrations.AlterField(
            model_name='concept',
            name='equations',
            field=djongo.models.fields.ArrayReferenceField(blank=True, on_delete=djongo.models.fields.ArrayReferenceField._on_delete, to='solver.Equation'),
        ),
    ]
