# Generated by Django 2.2.7 on 2019-11-14 03:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solver', '0003_auto_20191114_0315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equation',
            name='parent_concept',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equas', to='solver.Concept'),
        ),
    ]
