# Generated by Django 2.2.7 on 2019-11-14 03:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solver', '0004_auto_20191114_0324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='concept',
            name='attributes',
        ),
        migrations.RemoveField(
            model_name='concept',
            name='equations',
        ),
        migrations.AlterField(
            model_name='attribute',
            name='parent_concept',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='solver.Concept'),
        ),
        migrations.AlterField(
            model_name='equation',
            name='parent_concept',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equations', to='solver.Concept'),
        ),
    ]
