# Generated by Django 2.2.7 on 2019-11-16 20:44

from django.db import migrations
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('solver', '0006_auto_20191114_0332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concept',
            name='equations',
            field=djongo.models.fields.ArrayReferenceField(blank=True, default=list, on_delete=django.db.models.deletion.CASCADE, to='solver.Equation'),
        ),
    ]
