# Generated by Django 2.2.7 on 2019-11-16 20:55

from django.db import migrations
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('solver', '0007_auto_20191116_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concept',
            name='equations',
            field=djongo.models.fields.ArrayReferenceField(blank=True, default=list, on_delete=djongo.models.fields.ArrayReferenceField._on_delete, to='solver.Equation'),
        ),
    ]
