# Generated by Django 2.2.7 on 2019-11-18 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solver', '0009_auto_20191118_0721'),
    ]

    operations = [
        migrations.AddField(
            model_name='concept',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='concept',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
