# Generated by Django 2.2.7 on 2019-11-18 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solver', '0010_auto_20191118_0722'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='concept',
            name='description',
        ),
    ]
